config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', skip: :registrations
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'pages#home'
  resources :properties, only: [ :index, :show ]
  resources :posts, only: [ :index, :show ]

  namespace :admin do
    resources :properties, only: [ :new, :index, :create, :edit, :update, :destroy ] do
      resources :features, only: [ :new, :create ]
      resources :photos, only: [ :new, :create ]
    end
    resources :features, only: [ :edit, :update, :destroy ]
    resources :photos, only: [ :edit, :update, :destroy ]
    resources :posts, only: [ :new, :index, :create, :edit, :update, :destroy ]
    resources :reviews, only: [ :new, :index, :create, :edit, :update, :destroy ]
    resources :pages, only: [:index, :edit, :update]
    resources :communities, only: [:edit, :update]
  end
  resources :contact_emails, only: [:new, :create]

  get 'admin' => 'admin/properties#index'

  #Main redirects from old website
  get "/hpl-blog" => redirect("/posts")
  get "/book-now" => redirect("/properties")
  get "/the-lodges" => redirect("/properties")
  get "/cottages-in-the-country" => redirect("/properties?query[in_country]=true")
  get "/lodges-in-aviemore" => redirect("/properties?query[in_aviemore]=true")
  get "/hot-tub-page" => redirect("/properties?query[sauna_or_hot_tub]=true")
  get "/2---6-sleeper-lodges" => redirect("/properties")
  get "/7--12-sleeper-lodges" => redirect("/properties")

  #Lodge redirects from old website
  get "/douglas-cottage---sleeps-6" => redirect("/properties/4")
  get "/westcott---sleeps-6" => redirect("/properties/13")
  get "/the-bothy---sleeps-4" => redirect("/properties/9")
  get "/cairn-eilrig---sleeps-6" => redirect("/properties/3")
  get "/the-old-smithy---sleeps-4--2" => redirect("/properties/10")
  get "/riverside-lodge---sleeps-6" => redirect("/properties/6")
  get "/rymore-wood-lodge---sleeps-8" => redirect("/properties/7")
  get "/tomdhu-lodge---sleep-8" => redirect("/properties/11")
  get "/trails-end-lodge---sleeps-8" => redirect("/properties/12")
  get "/foresters-lodge---sleeps-10" => redirect("/properties/5")
  get "/burnbrae-lodge---sleeps-8" => redirect("/properties/2")
  get "/alltnacriche---sleeps-10" => redirect("/properties/1")
  get "/smithy--riverside-lodge---sleeps-10--2" => redirect("/properties/8")

  #Other page redirects from old website
  get "/contact" => redirect("/pages/contact")
  get "/go-catered" => redirect("/pages/go_catered")
  get "/about-us" => redirect("/pages/about_us")
  get "/about-the-area" => redirect("/pages/about_the_area")
  get "/pet-friendly" => redirect("/pages/pet_friendly")
  get "/families" => redirect("/pages/families")
  get "/reviews" => redirect("/pages/reviews")
  get "/own-a-property" => redirect("/pages/own_a_property")
  get "/terms-and-conditions" => redirect("/pages/terms_and_conditions")
  get "/privacy-policy" => redirect("/pages/privacy_policy")
  get "/frequently-asked-questions" => redirect("/pages/frequently_asked_questions")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/about_the_area'
  get 'pages/contact'
  get 'pages/own_a_property'
  get 'pages/go_catered'
  get 'pages/pet_friendly'
  get 'pages/families'
  get 'pages/about_us'
  get 'pages/terms_and_conditions'
  get 'pages/frequently_asked_questions'
  get 'pages/reviews'
  get 'pages/privacy_policy'
  get 'pages/cookies'
  get 'pages/sustainability'
  get 'pages/sustainability_policy'
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < Admin::AdminController
  before_action :find_review, except: [:new, :create, :index]

  def new
    @review = Review.new
  end

  def index
    @reviews = Review.all
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to admin_reviews_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to admin_reviews_path
    else
      render :edit
    end
  end

  def destroy
    if @review.destroy
      redirect_to admin_reviews_path
    else
      flash[:alert] = "Error deleting review!"
    end
  end

  private

  def find_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :date, :property_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

end

app/views/admin/reviews/_review_form.html.erb
<%= simple_form_for ([:admin, @review]) do |f| %>
  <%= f.association :property, label: "Review for Lodge:" %>
  <%= f.input :content, label: "Review (no need to add quotation marks)" %>
  <%= f.input :date, label: "Date of review", placeholder: "e.g. June 2018" %>
  <%= f.submit "Submit", class: "btn btn-success" %>
<% end %>

app/views/admin/reviews/edit.html.erb
<div class="container">
  <h1>Update fields for <%= @review.property.name %></h1>
  <%= render 'review_form' %>
</div>

app/views/admin/reviews/index.html.erb
<h1>Reviews</h1>

<div class="form-group">
  <%= link_to 'New Review', new_admin_review_path, class: 'btn btn-default' %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Property</th>
      <th>Review content</th>
      <th>Date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.id %></td>
        <td><%= review.property.name %></td>
        <td><%= review.content %></td>
        <td><%= review.date %></td>
        <td>
          <%= link_to 'Edit', edit_admin_review_path(review), class: 'btn btn-default' %>
          <%= link_to 'Delete', [:admin, review], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/reviews/new.html.erb
<div class="container">
  <h1>Add a new review</h1>
  <%= simple_form_for ([:admin, @review]) do |f| %>
    <%= f.association :property %>
    <%= f.input :content %>
    <%= f.input :date, placeholder: "e.g. June 2018" %>
    <%= f.submit "Add a review", class: "btn btn-success" %>
  <% end %>
</div>