config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', skip: :registrations
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'pages#home'
  resources :properties, only: [ :index, :show ]
  resources :posts, only: [ :index, :show ]

  namespace :admin do
    resources :properties, only: [ :new, :index, :create, :edit, :update, :destroy ] do
      resources :features, only: [ :new, :create ]
      resources :photos, only: [ :new, :create ]
    end
    resources :features, only: [ :edit, :update, :destroy ]
    resources :photos, only: [ :edit, :update, :destroy ]
    resources :posts, only: [ :new, :index, :create, :edit, :update, :destroy ]
    resources :reviews, only: [ :new, :index, :create, :edit, :update, :destroy ]
    resources :pages, only: [:index, :edit, :update]
    resources :communities, only: [:edit, :update]
  end
  resources :contact_emails, only: [:new, :create]

  get 'admin' => 'admin/properties#index'

  #Main redirects from old website
  get "/hpl-blog" => redirect("/posts")
  get "/book-now" => redirect("/properties")
  get "/the-lodges" => redirect("/properties")
  get "/cottages-in-the-country" => redirect("/properties?query[in_country]=true")
  get "/lodges-in-aviemore" => redirect("/properties?query[in_aviemore]=true")
  get "/hot-tub-page" => redirect("/properties?query[sauna_or_hot_tub]=true")
  get "/2---6-sleeper-lodges" => redirect("/properties")
  get "/7--12-sleeper-lodges" => redirect("/properties")

  #Lodge redirects from old website
  get "/douglas-cottage---sleeps-6" => redirect("/properties/4")
  get "/westcott---sleeps-6" => redirect("/properties/13")
  get "/the-bothy---sleeps-4" => redirect("/properties/9")
  get "/cairn-eilrig---sleeps-6" => redirect("/properties/3")
  get "/the-old-smithy---sleeps-4--2" => redirect("/properties/10")
  get "/riverside-lodge---sleeps-6" => redirect("/properties/6")
  get "/rymore-wood-lodge---sleeps-8" => redirect("/properties/7")
  get "/tomdhu-lodge---sleep-8" => redirect("/properties/11")
  get "/trails-end-lodge---sleeps-8" => redirect("/properties/12")
  get "/foresters-lodge---sleeps-10" => redirect("/properties/5")
  get "/burnbrae-lodge---sleeps-8" => redirect("/properties/2")
  get "/alltnacriche---sleeps-10" => redirect("/properties/1")
  get "/smithy--riverside-lodge---sleeps-10--2" => redirect("/properties/8")

  #Other page redirects from old website
  get "/contact" => redirect("/pages/contact")
  get "/go-catered" => redirect("/pages/go_catered")
  get "/about-us" => redirect("/pages/about_us")
  get "/about-the-area" => redirect("/pages/about_the_area")
  get "/pet-friendly" => redirect("/pages/pet_friendly")
  get "/families" => redirect("/pages/families")
  get "/reviews" => redirect("/pages/reviews")
  get "/own-a-property" => redirect("/pages/own_a_property")
  get "/terms-and-conditions" => redirect("/pages/terms_and_conditions")
  get "/privacy-policy" => redirect("/pages/privacy_policy")
  get "/frequently-asked-questions" => redirect("/pages/frequently_asked_questions")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/about_the_area'
  get 'pages/contact'
  get 'pages/own_a_property'
  get 'pages/go_catered'
  get 'pages/pet_friendly'
  get 'pages/families'
  get 'pages/about_us'
  get 'pages/terms_and_conditions'
  get 'pages/frequently_asked_questions'
  get 'pages/reviews'
  get 'pages/privacy_policy'
  get 'pages/cookies'
  get 'pages/sustainability'
  get 'pages/sustainability_policy'
end

app/views/shared/_availability-checker.html.erb
<div class="availability-checker">
  <%= simple_form_for :search, url: properties_path, method: :get, html: { id: "properties-search" } do |t| %>
    <% if session[:search] %>
      <%= t.input :start_date, placeholder: "Arrival date", label: false, as: :string, input_html: { value: session[:search][:start_date], class: "start-date-picker", required: true } %>
      <%= t.input :nights, placeholder: "Number of nights", label: false, collection: [7, 14, 21], input_html: { id: "search-nights", required: true, value: session[:search][:nights] } %>
    <% else %>
      <%= t.input :start_date, placeholder: "Arrival date", label: false, as: :string, input_html: { class: "start-date-picker", required: true } %>
      <%= t.input :nights, placeholder: "Number of nights", label: false, collection: [7, 14, 21], input_html: { id: "search-nights", required: true } %>
    <% end %>
    <div class="text-center">
      <%= t.submit "CHECK AVAILABILITY", name: nil, class: "btn btn-success", :input_html => { id: 'products_search' } %>
    </div>
  <% end %>
</div>
<script>
  function dateSelected() {
    selection = $( ".start-date-picker" ).val()
    var day = new Date(selection);
    var d = day.getDay();
    if (d == 1) {
      $('#search-nights').html("<option value='4'>4 nights</option><option value='7'>7 nights</option><option value='11'>11 nights</option><option value='14'>14 nights</option><option value='18'>18 nights</option><option value='21'>21 nights</option>");
    }
    if (d == 5) {
      $('#search-nights').html("<option value='3'>3 nights</option><option value='7'>7 nights</option><option value='10'>10 nights</option><option value='14'>14 nights</option><option value='17'>17 nights</option><option value='21'>21 nights</option>");
    }
  }
  $(document).ready(function() {
    $('#search-nights').empty();
    $('.start-date-picker').change(function() {
      dateSelected();
    });
  });
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="handpicked-footer">
  <h5><span>Navigation</span></h5>
  <div class="handpicked-footer-links">
    <div class="handpicked-footer-top">
      <div class="handpicked-footer-text text-center">
        <p><%= link_to 'The Lodges', properties_path %></p>
        <p><%= link_to 'Go Catered?', pages_go_catered_path%></p>
        <p><%= link_to 'About Us', pages_about_us_path%></p>
        <p><%= link_to 'Contact', pages_contact_path%></p>
      </div>
      <div class="handpicked-footer-text text-center">
        <p><%= link_to 'Our Blog', posts_path %></p>
        <p><%= link_to 'Reviews', pages_reviews_path %></p>
      </div>
      <div class="handpicked-footer-text text-center">
        <p><%= link_to 'Own a Property?', pages_own_a_property_path %></p>
        <p><%= link_to 'Terms and Conditions', pages_terms_and_conditions_path %></p>
        <p><%= link_to 'Frequently Asked Questions', pages_frequently_asked_questions_path %></p>
        <p><%= link_to 'Seasgair Community', pages_sustainability_path %></p>
        <p><%= link_to 'Privacy Policy', pages_privacy_policy_path %></p>
      </div>
    </div>
  </div>
  <h5>Connect with Us</h5>
  <div class="handpicked-footer-bottom">
    <% if mobile_device? %>
      <div class="handpicked-footer-text text-center">
        <p>Bookings & Enquiries: 01479 420 670</p>
        <p><a href="mailto:hello@seasgairlodges.com">hello@seasgairlodges.com</a></p>
      </div>
    <% else %>
      <div class="handpicked-footer-text">
        <p>Bookings & Enquiries: 01479 420 670</p>
        <p><a href="mailto:hello@seasgairlodges.com">hello@seasgairlodges.com</a></p>
      </div>
    <% end %>
    <div class="handpicked-footer-image footer-space text-center">
      <%= image_tag("cairngorm-national-park.jpg", class: 'footer-image-pad') %>
      <%= image_tag("2019-winner.jpg", class: 'footer-image-pad') %>
      <%= image_tag("self-catering-finalist.png", class: 'footer-image-pad') %>
      <%= image_tag("green-tourism.jpg", class: 'footer-image-pad') %>
      <%= image_tag("logos/good_to_go.png", class: 'footer-image-pad', style: "background-color: white; padding: 0;") %>
      <%= image_tag("opayo_logo.png", class: 'footer-image-pad') %>
    </div>
    <div class="footer-icons text-center">
      <a href="https://www.facebook.com/SeasgairHandpickedLodges" target="blank"><%= fa_icon "facebook" %></a>
      <a href="https://www.instagram.com/seasgairhandpickedlodges" target="blank"><%= fa_icon "instagram" %></a>
    </div>
  </div>
  <div class="handpicked-footer-top">
  </div>
  <br>
  <div class="text-center">
    <p style="font-size: 12px;">Heather Management Ltd T/A Seasgair Lodges. Registered in Scotland. Registered office: Craigellachie House, Dalfaber Road, Aviemore, PH22 1PX.</p>
    <p style="font-size: 12px;">Company No: SC544248. VAT reg: 297678327</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<script src="//code.jquery.com/jquery-1.9.1.min.js"></script>
<div id="handpicked-navbar">
  <!-- <div id="handpicked-navbar-spacer"> -->
    <!-- Logo -->


    <!-- Right navigation - desktop -->
    <div class="handpicked-navbar-center hidden-xs hidden-sm">
      <%= link_to root_path, id: "handpicked-navbar-brand" do %>
        <%= image_tag "seasgair-logo.jpg" %>
      <% end %>
      <div class="handpicked-navbar-right hidden-xs hidden-sm">
        <div class="handpicked-navbar-item"><%= link_to 'Our Lodges', properties_path, { :class=>"handpicked-navbar-link" } %></div>
        <div class="handpicked-navbar-item"><%= link_to 'Seasgair Community', pages_sustainability_path, { :class=>"handpicked-navbar-link" } %></div>
        <div class="handpicked-navbar-item"><%= link_to 'About Us', pages_about_us_path, { :class=>"handpicked-navbar-link" } %></div>
        <div class="handpicked-navbar-item"><%= link_to 'Own a Property', pages_own_a_property_path, { :class=>"handpicked-navbar-link" } %></div>
        <div class="handpicked-navbar-item"><%= link_to 'Contact', pages_contact_path, { :class=>"handpicked-navbar-link" } %></div>
      </div>
    </div>
  <!-- </div> -->

  <!-- Dropdown for mobile only -->
  <div class="hidden-md hidden-lg">
    <%= link_to root_path, id: "handpicked-navbar-brand-small" do %>
      <%= image_tag "seasgair-logo.jpg" %>
    <% end %>
  </div>
  <div class="handpicked-navbar-item-mobile hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul id="main-dropdown" class="dropdown-menu dropdown-menu-right handpicked-navbar-dropdown-menu text-center">
        <li><%= link_to 'Our Lodges', properties_path, tabindex:"-1" %></li>
        <li><%= link_to 'Seasgair Community', pages_sustainability_path, tabindex:"-1" %></li>
        <li><%= link_to 'About Us', pages_about_us_path, tabindex:"-1" %></li>
        <li><%= link_to 'Own a Property', pages_own_a_property_path, tabindex:"-1" %></li>
        <li><%= link_to 'Contact', pages_contact_path, tabindex:"-1" %></li>
      </ul>
    </div>
  </div>
</div>
<script>
$(document).ready(function(){
  $('.dropdown-submenu a.test').on("click", function(e){
    $(this).next('ul').toggle();
    e.stopPropagation();
    e.preventDefault();
  });
});
</script>

app/views/shared/_page-search.html.erb
<div class="grey-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="text-line before text-center">
          <h3>Ready to book?</h3>
        </div>
      </div>
      <div class="col-xs-12 col-md-4 col-md-offset-4">
        <%= render 'shared/availability-checker' %>
      </div>
    </div>
  </div>
</div>