config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', skip: :registrations
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'pages#home'
  resources :properties, only: [ :index, :show ]
  resources :posts, only: [ :index, :show ]

  namespace :admin do
    resources :properties, only: [ :new, :index, :create, :edit, :update, :destroy ] do
      resources :features, only: [ :new, :create ]
      resources :photos, only: [ :new, :create ]
    end
    resources :features, only: [ :edit, :update, :destroy ]
    resources :photos, only: [ :edit, :update, :destroy ]
    resources :posts, only: [ :new, :index, :create, :edit, :update, :destroy ]
    resources :reviews, only: [ :new, :index, :create, :edit, :update, :destroy ]
    resources :pages, only: [:index, :edit, :update]
    resources :communities, only: [:edit, :update]
  end
  resources :contact_emails, only: [:new, :create]

  get 'admin' => 'admin/properties#index'

  #Main redirects from old website
  get "/hpl-blog" => redirect("/posts")
  get "/book-now" => redirect("/properties")
  get "/the-lodges" => redirect("/properties")
  get "/cottages-in-the-country" => redirect("/properties?query[in_country]=true")
  get "/lodges-in-aviemore" => redirect("/properties?query[in_aviemore]=true")
  get "/hot-tub-page" => redirect("/properties?query[sauna_or_hot_tub]=true")
  get "/2---6-sleeper-lodges" => redirect("/properties")
  get "/7--12-sleeper-lodges" => redirect("/properties")

  #Lodge redirects from old website
  get "/douglas-cottage---sleeps-6" => redirect("/properties/4")
  get "/westcott---sleeps-6" => redirect("/properties/13")
  get "/the-bothy---sleeps-4" => redirect("/properties/9")
  get "/cairn-eilrig---sleeps-6" => redirect("/properties/3")
  get "/the-old-smithy---sleeps-4--2" => redirect("/properties/10")
  get "/riverside-lodge---sleeps-6" => redirect("/properties/6")
  get "/rymore-wood-lodge---sleeps-8" => redirect("/properties/7")
  get "/tomdhu-lodge---sleep-8" => redirect("/properties/11")
  get "/trails-end-lodge---sleeps-8" => redirect("/properties/12")
  get "/foresters-lodge---sleeps-10" => redirect("/properties/5")
  get "/burnbrae-lodge---sleeps-8" => redirect("/properties/2")
  get "/alltnacriche---sleeps-10" => redirect("/properties/1")
  get "/smithy--riverside-lodge---sleeps-10--2" => redirect("/properties/8")

  #Other page redirects from old website
  get "/contact" => redirect("/pages/contact")
  get "/go-catered" => redirect("/pages/go_catered")
  get "/about-us" => redirect("/pages/about_us")
  get "/about-the-area" => redirect("/pages/about_the_area")
  get "/pet-friendly" => redirect("/pages/pet_friendly")
  get "/families" => redirect("/pages/families")
  get "/reviews" => redirect("/pages/reviews")
  get "/own-a-property" => redirect("/pages/own_a_property")
  get "/terms-and-conditions" => redirect("/pages/terms_and_conditions")
  get "/privacy-policy" => redirect("/pages/privacy_policy")
  get "/frequently-asked-questions" => redirect("/pages/frequently_asked_questions")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/about_the_area'
  get 'pages/contact'
  get 'pages/own_a_property'
  get 'pages/go_catered'
  get 'pages/pet_friendly'
  get 'pages/families'
  get 'pages/about_us'
  get 'pages/terms_and_conditions'
  get 'pages/frequently_asked_questions'
  get 'pages/reviews'
  get 'pages/privacy_policy'
  get 'pages/cookies'
  get 'pages/sustainability'
  get 'pages/sustainability_policy'
end

app/models/property.rb
require 'uploads'

class Property < ApplicationRecord
  include Filterable
  attr_accessor :price, :book_link, :price_message, :start_date, :nights
  scope :wood_stove, -> (wood_stove) { where wood_stove: wood_stove }
  scope :hot_tub, -> (hot_tub) { where hot_tub: hot_tub }
  scope :pet_friendly, -> (pet_friendly) { where pet_friendly: pet_friendly }
  scope :sauna, -> (sauna) { where sauna: true }
  scope :in_aviemore, -> (in_aviemore) { where in_aviemore: in_aviemore }
  scope :in_country, -> (in_country) { where in_country: in_country }
  scope :sauna_or_hot_tub, -> (sauna_or_hot_tub) { hot_tub(true).or(sauna(true)) }

  mount_uploader :hero_image, PhotoUploader
  has_one_attached :main_image
  mount_uploader :floorplan, PhotoUploader
  has_one_attached :floorplan_image
  validates :code, uniqueness: true, numericality: { only_integer: true }
  validates :meta_title, length: { maximum: 80 }
  validates :meta_description, length: { maximum: 300 }
  validates :headline, length: { maximum: 150 }
  validates :we_love, presence: true
  validates :sleeps, :bedrooms, :bathrooms, numericality: { only_integer: true }
  has_many :photos, dependent: :destroy
  scope :with_attached_photos, -> { includes(:photos).merge(Photo.with_attached_picture) }
  has_many :reviews, dependent: :destroy
  has_many :features, dependent: :destroy
  accepts_nested_attributes_for :features,
    allow_destroy: true
  accepts_nested_attributes_for :photos,
    allow_destroy: true,
    :reject_if => proc { |att| att[:image].blank? }
  before_destroy :purge_active_storage
  validates :main_image, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  validates :floorplan_image, content_type: ['image/png', 'image/jpg', 'image/jpeg']

  def main_image_card_variant
    variation = ActiveStorage::Variation.new(Uploads.resize_to_fit(width: 600, height: 550, quality: 80, blob: main_image.blob))
    ActiveStorage::Variant.new(main_image.blob, variation)
  end

  def main_image_map_variant
    variation = ActiveStorage::Variation.new(Uploads.resize_to_fit(width: 400, height: 300, quality: 80, blob: main_image.blob))
    ActiveStorage::Variant.new(main_image.blob, variation)
  end

  def main_image_meta_variant
    variation = ActiveStorage::Variation.new(Uploads.resize_to_fit(width: 1200, height: 630, quality: 80, blob: main_image.blob))
    ActiveStorage::Variant.new(main_image.blob, variation)
  end

  def main_image_show_variant
    variation = ActiveStorage::Variation.new(Uploads.resize_to_fit(width: 1200, height: 800, quality: 80, blob: main_image.blob))
    ActiveStorage::Variant.new(main_image.blob, variation)
  end

  def main_image_thumbnail_variant
    variation = ActiveStorage::Variation.new(Uploads.resize_to_fit(width: 300, height: 300, quality: 70, blob: main_image.blob))
    ActiveStorage::Variant.new(main_image.blob, variation)
  end

  # def floorplan_image_variant
  # end

  private

  def purge_active_storage
    main_image.purge
    floorplan_image.purge
  end
end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < Admin::AdminController
  before_action :find_property, except: [:new, :create, :index]

  def index
    @properties = Property.order(:id)
  end

  def new
    @property = Property.new
    @property.photos.build
    @property.features.build
  end

  def create
    @property = Property.new(property_params)
    if @property.save
      flash[:notice] = "Successfully created property!"
      redirect_to admin_properties_path
    else
      render :new
    end
  end

  def edit
    @property.photos.build
    @property.features.build
    @photos = @property.photos
    @features = @property.features
  end

  def update
    if @property.update(property_params)
      redirect_to admin_properties_path
    else
      render :edit
    end
  end

  def destroy
    if @property.destroy
      redirect_to admin_properties_path
      flash[:notice] = "Successfully deleted property!"
    else
      flash[:alert] = "Error deleting property!"
    end
  end

  private

  def find_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:code, :in_aviemore, :in_country, :enabled, :name, :sleeps, :headline, :description, :min_daily_price, :bedrooms, :bathrooms,
      :wood_stove, :hot_tub, :pet_friendly, :sauna, :games_room, :features, :we_love, :guests_love, :meta_title, :meta_description, :latitude, :longitude, :hero_image, :main_image, :floorplan, :floorplan_image, :video_iframe, :tour_iframe, photos_attributes: [:id, :image, :key], features_attributes: [:id, :name, :key])
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  require 'open-uri'

  def index
    @max_sleeps ||= Property.where(enabled: true).order("sleeps DESC").first.sleeps
    if params[:search].present?
      @properties = available_properties + unavailable_properties
      store_search(params)
      respond_to do |format|
        format.html
        format.js
      end
    elsif params[:query].present?
      @properties = Property.filter(params[:query].slice(:wood_stove, :pet_friendly, :hot_tub, :sauna, :in_aviemore, :in_country, :sauna_or_hot_tub)).where(enabled: true).order(Arel.sql("random()")).with_attached_main_image.with_attached_photos
    else
      @properties = Property.where(enabled: true).order(Arel.sql("random()")).with_attached_main_image.with_attached_photos
    end
  end

  def show
    if params[:book_link].present?
      @property = Property.where(enabled: true).find(params[:id])
      @price = params[:price]
      @book_link = params[:book_link]
      @start_date = Date.parse params[:start_date]
      @end_date = @start_date + params[:nights].to_i
      @days = params[:nights]
    else
      @property = Property.where(enabled: true).find(params[:id])
    end
  end

  private

  def store_search(params)
    session[:search] = params[:search]
  end

  def available_properties
    if params[:search][:start_date].present? && params[:search][:nights].present?
      @available_properties = Property.where(enabled: true).where(location).where("sleeps >= ?", params[:search][:sleeps].to_i).order(Arel.sql("random()")).with_attached_main_image.with_attached_photos.search(params)
    else
      @available_properties = Property.where(enabled: true).where(location).where("sleeps >= ?", params[:search][:sleeps].to_i).order(Arel.sql("random()")).with_attached_main_image.with_attached_photos
    end
  end

  def unavailable_properties
    @unavailable_properties = Property.where.not(id: @available_properties).where(enabled: true).where("sleeps >= ?", params[:search][:sleeps].to_i).where(location).order(Arel.sql("random()")).with_attached_main_image.with_attached_photos
  end

  def location
    return { in_aviemore: true } if params[:search][:location] == 'Cairngorms'

    return { in_country: true } if params[:search][:location] == 'Perthshire'

    return ''
  end
end

app/views/admin/properties/_feature.html.erb
<% @property.features.each do |feature| %>
  <% unless feature.name.blank? %>
    <div data-feature-id="<%= feature.id %>">
      <div class="col-xs-12 col-sm-4">
        <div class="white-card">
          <% if feature.key? %>
            <p><strong><%= feature.name %> | <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Key Feature</strong></p>
          <% else %>
            <p><strong><%= feature.name %></strong></p>
          <% end %>
          <%= link_to 'Edit', edit_admin_feature_path(feature),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-default'} %>
          <%= link_to 'Delete', [:admin, feature], method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'btn btn-danger' %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/properties/_photo.html.erb
<% i = 2 %>
<% @property.photos.with_attached_picture.order(created_at: :asc).each do |photo| %>
  <% if photo.picture.attached? && photo.picture.attachment.blob.present? && photo.picture.attachment.blob.persisted? %>
    <div data-photo-id="<%= photo.id %>">
      <div class="col-xs-12 col-sm-3">
        <div class="white-card">
          <p><strong>Photo: <%= i %></strong></p>
          <% if photo.key? %>
            <p><strong>Key Photo: <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></strong></p>
          <% end %>
          <p></p>
          <div class="link-card-cloudinary image-margin" style="background-image: url('<%= rails_representation_url photo.picture_card_variant %>');">
          </div>
          <%= link_to 'Edit', edit_admin_photo_path(photo),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-default'} %>
          <%= link_to 'Delete', [:admin, photo], method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'btn btn-danger' %>
        </div>
      </div>
    </div>
  <% end %>
  <% i += 1 %>
<% end %>

app/views/admin/properties/_property_form.html.erb
<%= simple_form_for ([:admin, @property]) do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="text-line before grey text-center">
        <h3>Lodge SEO</h3>
      </div>
      <br>
    </div>
  </div>
  <%= f.input :meta_title %> <p>Limit of 80 characters, Google will likely truncate at around 70 characters</p>
  <%= f.input :meta_description %> <p>Limit of 300 characters</p>
  <div class="row">
    <div class="col-xs-12">
      <div class="text-line before grey text-center">
        <h3>Lodge Details</h3>
      </div>
      <br>
    </div>
  </div>
  <%= f.input :enabled, label: "Lodge visible and active on website" %>
  <%= f.input :code, label: "SuperControl Property Code" %>
  <%= f.input :min_daily_price, label: "SuperControl: Minimum daily price of lodge" %>
  <%= f.input :name, label: "Lodge Name" %>
  <%= f.input :sleeps %>
  <%= f.input :bedrooms, label: "No. of bedrooms" %>
  <%= f.input :bathrooms, label: "No. of bathrooms" %>
  <%= f.input :headline, label: "Lodge Headline" %>
  <%= f.input :description, label: "Lodge's main description" %>
  <%= f.input :we_love, label: "What we love (do not add quotation marks)" %>
  <%= f.input :guests_love, label: "What guests love (do not add quotation marks)" %>
  <%= f.input :wood_stove %>
  <%= f.input :hot_tub %>
  <%= f.input :games_room %>
  <%= f.input :pet_friendly %>
  <%= f.input :sauna %>
  <%= f.input :video_iframe %>
  <%= f.input :tour_iframe %>
  <div class="row">
    <div class="col-xs-12">
      <div class="text-line before grey text-center">
        <h3>Lodge Location</h3>
      </div>
      <br>
    </div>
  </div>
  <%= f.input :in_aviemore, label: "Lodge in Cairngorms?" %>
  <%= f.input :in_country, label: "Lodge in Perthshire?" %>
  <p><strong>For the latitude and longitude of your property, please visit <a href="https://www.latlong.net/" target="blank">https://www.latlong.net/</a></strong></p>
  <%= f.input :latitude %>
  <%= f.input :longitude %>
  <%= f.input :floorplan_image, label: "Lodge floorplan" %>
  <%= f.input :main_image, label: "Main photo" %>
  <% if @property.main_image.attached? && @property.main_image.attachment.blob.present? && @property.main_image.attachment.blob.persisted? %>
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class="white-card">
          <p><strong>Photo: 1 (new main image model)</strong></p>
          <div class="link-card-cloudinary" style="background-image: url('<%= rails_representation_url @property.main_image_card_variant %>');">
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= f.button :submit, class: "btn-lg btn-success" %>
<% end %>
<div class="row">
  <div class="col-xs-12">
    <div class="text-line before grey text-center">
      <h3>Lodge Features</h3>
    </div>
    <br>
  </div>
</div>
<% if @property.id.nil? %>
  <div class="white-card text-center">
    <h3>Please create a property record first (above) before you can add features</h3>
    <h4>Once all details are added, then enable the property to make it live on your website</h4>
  </div>
  <br>
<% else %>
  <%= link_to 'Add feature', new_admin_property_feature_path(@property),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-default'} %>
  <br>
  <br>
  <div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
  <% if @property.features.present? %>
    <div class="row" id="features">
      <%= render 'feature' %>
    </div>
  <% end %>
  <br>
<% end %>
<div class="row">
  <div class="col-xs-12">
    <div class="text-line before grey text-center">
      <h3>Lodge Images</h3>
      <p><strong>Please select only 2 'key photos'</strong> - the main image (above) will be the leading photo for the property</p>
    </div>
    <br>
  </div>
</div>
<% if @property.id.nil? %>
  <div class="white-card text-center">
    <h3>Please create a property record first (above) before you can add photos</h3>
    <h4>Once all details are added, then enable the property to make it live on your website</h4>
  </div>
  <br>
<% else %>
  <%= link_to 'Add photo', new_admin_property_photo_path(@property),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-default'} %>
  <br>
  <br>
  <% if @property.photos.present? %>
    <div class="row" id="photos">
      <%= render 'photo' %>
    </div>
  <% end %>
  <br>
<% end %>
<div id="spinner">
  <div class="spinner"></div>
</div>

app/views/admin/properties/edit.html.erb
<div class="container">
  <h1>Update fields for <%= @property.name %></h1>
  <%= render 'property_form' %>
</div>

app/views/admin/properties/index.html.erb
<h1>Properties</h1>

<div class="form-group">
  <%= link_to 'New Property', new_admin_property_path, class: 'btn btn-default' %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Property</th>
      <th>Active on site</th>
      <th>Tagline</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.id %></td>
        <td><%= link_to property.name, [property] %></td>
        <td>
          <% if property.enabled? %>
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <% else %>
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end %>
        </td>
        <td><%= property.headline&.truncate(60) %></td>
        <td>
          <%= link_to 'Edit', edit_admin_property_path(property), class: 'btn btn-default' %>
          <%= link_to 'Delete', [:admin, property], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/properties/new.html.erb
<div class="container">
  <h1>Create a new lodge</h1>
  <div class="white-card text-center">
    <h3>A note on creating properties</h3>
    <h4>Keep the lodge disabled until you have completed entering all relevant details. You can always save a draft and come back. When ready, enable the property to make it live on your website.</h4>
    <h4>Please note: you will need to create a property record first (just enter the basic details and submit) before you will be able to add any features or photos</h4>
  </div>
  <%= render 'property_form' %>
</div>