config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin', skip: :registrations
  mount Ckeditor::Engine => '/ckeditor'
  root to: 'pages#home'
  resources :properties, only: [ :index, :show ]
  resources :posts, only: [ :index, :show ]

  namespace :admin do
    resources :properties, only: [ :new, :index, :create, :edit, :update, :destroy ] do
      resources :features, only: [ :new, :create ]
      resources :photos, only: [ :new, :create ]
    end
    resources :features, only: [ :edit, :update, :destroy ]
    resources :photos, only: [ :edit, :update, :destroy ]
    resources :posts, only: [ :new, :index, :create, :edit, :update, :destroy ]
    resources :reviews, only: [ :new, :index, :create, :edit, :update, :destroy ]
    resources :pages, only: [:index, :edit, :update]
    resources :communities, only: [:edit, :update]
  end
  resources :contact_emails, only: [:new, :create]

  get 'admin' => 'admin/properties#index'

  #Main redirects from old website
  get "/hpl-blog" => redirect("/posts")
  get "/book-now" => redirect("/properties")
  get "/the-lodges" => redirect("/properties")
  get "/cottages-in-the-country" => redirect("/properties?query[in_country]=true")
  get "/lodges-in-aviemore" => redirect("/properties?query[in_aviemore]=true")
  get "/hot-tub-page" => redirect("/properties?query[sauna_or_hot_tub]=true")
  get "/2---6-sleeper-lodges" => redirect("/properties")
  get "/7--12-sleeper-lodges" => redirect("/properties")

  #Lodge redirects from old website
  get "/douglas-cottage---sleeps-6" => redirect("/properties/4")
  get "/westcott---sleeps-6" => redirect("/properties/13")
  get "/the-bothy---sleeps-4" => redirect("/properties/9")
  get "/cairn-eilrig---sleeps-6" => redirect("/properties/3")
  get "/the-old-smithy---sleeps-4--2" => redirect("/properties/10")
  get "/riverside-lodge---sleeps-6" => redirect("/properties/6")
  get "/rymore-wood-lodge---sleeps-8" => redirect("/properties/7")
  get "/tomdhu-lodge---sleep-8" => redirect("/properties/11")
  get "/trails-end-lodge---sleeps-8" => redirect("/properties/12")
  get "/foresters-lodge---sleeps-10" => redirect("/properties/5")
  get "/burnbrae-lodge---sleeps-8" => redirect("/properties/2")
  get "/alltnacriche---sleeps-10" => redirect("/properties/1")
  get "/smithy--riverside-lodge---sleeps-10--2" => redirect("/properties/8")

  #Other page redirects from old website
  get "/contact" => redirect("/pages/contact")
  get "/go-catered" => redirect("/pages/go_catered")
  get "/about-us" => redirect("/pages/about_us")
  get "/about-the-area" => redirect("/pages/about_the_area")
  get "/pet-friendly" => redirect("/pages/pet_friendly")
  get "/families" => redirect("/pages/families")
  get "/reviews" => redirect("/pages/reviews")
  get "/own-a-property" => redirect("/pages/own_a_property")
  get "/terms-and-conditions" => redirect("/pages/terms_and_conditions")
  get "/privacy-policy" => redirect("/pages/privacy_policy")
  get "/frequently-asked-questions" => redirect("/pages/frequently_asked_questions")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/about_the_area'
  get 'pages/contact'
  get 'pages/own_a_property'
  get 'pages/go_catered'
  get 'pages/pet_friendly'
  get 'pages/families'
  get 'pages/about_us'
  get 'pages/terms_and_conditions'
  get 'pages/frequently_asked_questions'
  get 'pages/reviews'
  get 'pages/privacy_policy'
  get 'pages/cookies'
  get 'pages/sustainability'
  get 'pages/sustainability_policy'
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Admin', admin_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sections <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Properties', admin_properties_path %></li>
            <li><%= link_to 'Posts', admin_posts_path %></li>
            <li><%= link_to 'Reviews', admin_reviews_path %></li>
            <li><%= link_to 'Pages', admin_pages_path %></li>
            <li><%= link_to 'Community', edit_admin_community_path(Community.first) %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <li><%= link_to 'Sign out', destroy_admin_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_admin_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seasgair Admin Panel</title>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <%= render 'shared/flashes' %>
  <div class="container">
    <%= yield %>
  </div>

  <%= javascript_pack_tag 'application' %>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global Site Tag (gtag.js) - Google Analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-85678386-1', 'auto');
      ga('send', 'pageview');
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Favicon stuff -->
    <%= favicon_link_tag 'favicons/favicon.ico' %>
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.css' rel='stylesheet' />
    <!-- Facebook Pixel Code -->
    <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '442568402834634');
      fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=442568402834634&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Facebook Pixel Code -->
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
    <script>
      window.addEventListener("load", function(){
      window.cookieconsent.initialise({
        "palette": {
          "popup": {
            "background": "#f9fcfc",
            "text": "#4f4f4f"
          },
          "button": {
            "background": "#82aeb1",
            "text": "#ffffff"
          }
        },
        "content": {
          "href": "/pages/cookies"
        }
      })});
    </script>
  </head>
  <body>
    <div class="alert alert-info alert-dismissible" role="alert">
      <a class="white-link" href="https://www.seasgairlodges.com/posts/57">For more information on our response to Coronavirus (COVID-19) please click here.</a>
    </div>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <!-- <div id="main-content"> -->
      <%= yield %>
    <!-- </div> -->
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>